/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './my-service.module';
import * as i2 from '@angular/common/http';
import * as i3 from '@angular/common';
export const MyServiceModuleNgFactory:i0.NgModuleFactory<i1.MyServiceModule> = i0.ɵcmf(i1.MyServiceModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.HttpXsrfTokenExtractor,i2.ɵg,[i3.DOCUMENT,i0.PLATFORM_ID,i2.ɵe]),i0.ɵmpd(4608,
          i2.ɵh,i2.ɵh,[i2.HttpXsrfTokenExtractor,i2.ɵf]),i0.ɵmpd(5120,i2.HTTP_INTERCEPTORS,
          (p0_0:any) => {
            return [p0_0];
          },[i2.ɵh]),i0.ɵmpd(4608,i2.ɵd,i2.ɵd,([] as any[])),i0.ɵmpd(6144,i2.XhrFactory,
          (null as any),[i2.ɵd]),i0.ɵmpd(4608,i2.HttpXhrBackend,i2.HttpXhrBackend,
          [i2.XhrFactory]),i0.ɵmpd(6144,i2.HttpBackend,(null as any),[i2.HttpXhrBackend]),
          i0.ɵmpd(5120,i2.HttpHandler,i2.ɵinterceptingHandler,[i2.HttpBackend,[2,i2.HTTP_INTERCEPTORS]]),
          i0.ɵmpd(4608,i2.HttpClient,i2.HttpClient,[i2.HttpHandler]),i0.ɵmpd(512,i2.HttpClientXsrfModule,
              i2.HttpClientXsrfModule,([] as any[])),i0.ɵmpd(512,i2.HttpClientModule,
              i2.HttpClientModule,([] as any[])),i0.ɵmpd(512,i1.MyServiceModule,i1.MyServiceModule,
              [[3,i1.MyServiceModule]]),i0.ɵmpd(256,i2.ɵe,'XSRF-TOKEN',([] as any[])),
          i0.ɵmpd(256,i2.ɵf,'X-XSRF-TOKEN',([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovR0lUL2dpdGh1Yi92YWx1ZGlvL2FuZ3VsYXItc2VydmljZS1tb2R1bGUvc3JjL215LXNlcnZpY2UubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0dJVC9naXRodWIvdmFsdWRpby9hbmd1bGFyLXNlcnZpY2UtbW9kdWxlL3NyYy9teS1zZXJ2aWNlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
